// Reverse mode hint content — see docs/reverse-hint-content-guidelines.md
// for the rules this data follows: concrete nouns/intrinsic traits over
// bare adjectives, never name a separate object (especially not another
// word actually in this game's word bank), at most one strongly-distinctive
// trait per word so no two hints combo into an instant giveaway, and no
// duplicate hint within one word's own list.
//
// Full 99/99 word coverage. Keys must match a words.js entry's w[0] exactly
// (secretWord in game.js).
export const REVERSE_HINTS = {
  // ==================== Animal ====================
  Dog: [
    { theme: 'Purpose', hint: 'Guards' },
    { theme: 'Material', hint: 'Fur' },
    { theme: 'Shape', hint: 'Four legs' },
    { theme: 'Color', hint: 'Brown' },
    { theme: 'Sensory', hint: 'Panting' },
    { theme: 'Location', hint: 'Backyard' },
    { theme: 'Size', hint: 'Lap-sized' },
    { theme: 'Shape', hint: 'Wagging tail' },
  ],
  Cat: [
    { theme: 'Purpose', hint: 'Grooms itself' },
    { theme: 'Material', hint: 'Fur' },
    { theme: 'Shape', hint: 'Four legs' },
    { theme: 'Color', hint: 'Neutral' },
    { theme: 'Sensory', hint: 'Padding' },
    { theme: 'Location', hint: 'Backyard' },
    { theme: 'Size', hint: 'Lap-sized' },
    { theme: 'Shape', hint: 'Whiskers' },
  ],
  Frog: [
    { theme: 'Purpose', hint: 'Hops' },
    { theme: 'Material', hint: 'Damp skin' },
    { theme: 'Shape', hint: 'Four legs' },
    { theme: 'Color', hint: 'Neutral' },
    { theme: 'Sensory', hint: 'Camouflaged' },
    { theme: 'Location', hint: 'Riverbank' },
    { theme: 'Size', hint: 'Fist-sized' },
    { theme: 'Shape', hint: 'Webbed feet' },
  ],
  Shark: [
    { theme: 'Purpose', hint: 'Hunts' },
    { theme: 'Material', hint: 'Rough skin' },
    { theme: 'Shape', hint: 'Fins' },
    { theme: 'Color', hint: 'Dark' },
    { theme: 'Sensory', hint: 'Splashing' },
    { theme: 'Location', hint: 'Coastline' },
    { theme: 'Size', hint: 'Massive' },
    { theme: 'Shape', hint: 'Sharp teeth' },
  ],
  Chicken: [
    { theme: 'Purpose', hint: 'Lays eggs' },
    { theme: 'Material', hint: 'Feathers' },
    { theme: 'Shape', hint: 'Two legs' },
    { theme: 'Color', hint: 'Pale' },
    { theme: 'Sensory', hint: 'Pecking' },
    { theme: 'Location', hint: 'Farmyard' },
    { theme: 'Size', hint: 'Fist-sized' },
    { theme: 'Shape', hint: 'Wings' },
  ],
  Horse: [
    { theme: 'Purpose', hint: 'Runs fast' },
    { theme: 'Material', hint: 'Mane' },
    { theme: 'Shape', hint: 'Four legs' },
    { theme: 'Color', hint: 'Brown' },
    { theme: 'Sensory', hint: 'Trotting' },
    { theme: 'Location', hint: 'Farmyard' },
    { theme: 'Size', hint: 'Massive' },
    { theme: 'Shape', hint: 'Hooves' },
  ],
  Cow: [
    { theme: 'Purpose', hint: 'Grazes' },
    { theme: 'Material', hint: 'Hide' },
    { theme: 'Shape', hint: 'Four legs' },
    { theme: 'Color', hint: 'Neutral' },
    { theme: 'Sensory', hint: 'Chewing' },
    { theme: 'Location', hint: 'Farmyard' },
    { theme: 'Size', hint: 'Massive' },
    { theme: 'Shape', hint: 'Horns' },
  ],
  Rabbit: [
    { theme: 'Purpose', hint: 'Hops' },
    { theme: 'Material', hint: 'Fur' },
    { theme: 'Shape', hint: 'Four legs' },
    { theme: 'Color', hint: 'Pale' },
    { theme: 'Sensory', hint: 'Scurrying' },
    { theme: 'Location', hint: 'Backyard' },
    { theme: 'Size', hint: 'Fist-sized' },
    { theme: 'Shape', hint: 'Long ears' },
  ],
  Bee: [
    { theme: 'Purpose', hint: 'Pollinates' },
    { theme: 'Material', hint: 'Delicate wings' },
    { theme: 'Shape', hint: 'Compact' },
    { theme: 'Color', hint: 'Bright' },
    { theme: 'Sensory', hint: 'Fluttering' },
    { theme: 'Location', hint: 'Meadow' },
    { theme: 'Size', hint: 'Tiny' },
    { theme: 'Shape', hint: 'Stinger' },
  ],
  Owl: [
    { theme: 'Purpose', hint: 'Hunts' },
    { theme: 'Material', hint: 'Feathers' },
    { theme: 'Shape', hint: 'Wings' },
    { theme: 'Color', hint: 'Neutral' },
    { theme: 'Sensory', hint: 'Gliding' },
    { theme: 'Location', hint: 'Wilderness' },
    { theme: 'Size', hint: 'Fist-sized' },
    { theme: 'Shape', hint: 'Large eyes' },
  ],
  Pig: [
    { theme: 'Purpose', hint: 'Grazes' },
    { theme: 'Material', hint: 'Hide' },
    { theme: 'Shape', hint: 'Four legs' },
    { theme: 'Color', hint: 'Pale' },
    { theme: 'Sensory', hint: 'Wallowing' },
    { theme: 'Location', hint: 'Farmyard' },
    { theme: 'Size', hint: 'Massive' },
    { theme: 'Shape', hint: 'Snout' },
  ],
  Snake: [
    { theme: 'Purpose', hint: 'Hunts' },
    { theme: 'Material', hint: 'Scales' },
    { theme: 'Shape', hint: 'Elongated' },
    { theme: 'Color', hint: 'Neutral' },
    { theme: 'Sensory', hint: 'Cold to the touch' },
    { theme: 'Location', hint: 'Wilderness' },
    { theme: 'Size', hint: 'Slender' },
    { theme: 'Shape', hint: 'Forked tongue' },
  ],
  Crab: [
    { theme: 'Purpose', hint: 'Scuttles' },
    { theme: 'Material', hint: 'Shell' },
    { theme: 'Shape', hint: 'Compact' },
    { theme: 'Color', hint: 'Neutral' },
    { theme: 'Sensory', hint: 'Clicking' },
    { theme: 'Location', hint: 'Coastline' },
    { theme: 'Size', hint: 'Fist-sized' },
    { theme: 'Shape', hint: 'Claws' },
  ],
  Elephant: [
    { theme: 'Purpose', hint: 'Carries loads' },
    { theme: 'Material', hint: 'Hide' },
    { theme: 'Shape', hint: 'Four legs' },
    { theme: 'Color', hint: 'Neutral' },
    { theme: 'Sensory', hint: 'Swaying' },
    { theme: 'Location', hint: 'Wilderness' },
    { theme: 'Size', hint: 'Massive' },
    { theme: 'Purpose', hint: 'Grazes' },
  ],
  Lion: [
    { theme: 'Purpose', hint: 'Hunts' },
    { theme: 'Material', hint: 'Fur' },
    { theme: 'Shape', hint: 'Mane' },
    { theme: 'Color', hint: 'Brown' },
    { theme: 'Sensory', hint: 'Prowling' },
    { theme: 'Location', hint: 'Wilderness' },
    { theme: 'Size', hint: 'Massive' },
    { theme: 'Purpose', hint: 'Leads a pack' },
  ],
  Penguin: [
    { theme: 'Purpose', hint: 'Swims' },
    { theme: 'Material', hint: 'Feathers' },
    { theme: 'Shape', hint: 'Sleek' },
    { theme: 'Color', hint: 'Dark' },
    { theme: 'Sensory', hint: 'Diving' },
    { theme: 'Location', hint: 'Coastline' },
    { theme: 'Size', hint: 'Fist-sized' },
    { theme: 'Shape', hint: 'Webbed feet' },
  ],
  Spider: [
    { theme: 'Purpose', hint: 'Hunts' },
    { theme: 'Material', hint: 'Exoskeleton' },
    { theme: 'Shape', hint: 'Compact' },
    { theme: 'Color', hint: 'Dark' },
    { theme: 'Sensory', hint: 'Lurking' },
    { theme: 'Location', hint: 'Backyard' },
    { theme: 'Size', hint: 'Tiny' },
    { theme: 'Shape', hint: 'Many legs' },
  ],
  Parrot: [
    { theme: 'Purpose', hint: 'Perches' },
    { theme: 'Material', hint: 'Feathers' },
    { theme: 'Shape', hint: 'Wings' },
    { theme: 'Color', hint: 'Bright' },
    { theme: 'Sensory', hint: 'Chattering' },
    { theme: 'Location', hint: 'Wilderness' },
    { theme: 'Size', hint: 'Fist-sized' },
    { theme: 'Shape', hint: 'Curved beak' },
  ],
  Salmon: [
    { theme: 'Purpose', hint: 'Swims' },
    { theme: 'Material', hint: 'Scales' },
    { theme: 'Shape', hint: 'Elongated' },
    { theme: 'Color', hint: 'Bright' },
    { theme: 'Sensory', hint: 'Splashing' },
    { theme: 'Location', hint: 'Riverbank' },
    { theme: 'Size', hint: 'Fist-sized' },
    { theme: 'Purpose', hint: 'Leaps' },
  ],
  Gorilla: [
    { theme: 'Purpose', hint: 'Climbs' },
    { theme: 'Material', hint: 'Fur' },
    { theme: 'Shape', hint: 'Broad chest' },
    { theme: 'Color', hint: 'Dark' },
    { theme: 'Sensory', hint: 'Grunting' },
    { theme: 'Location', hint: 'Wilderness' },
    { theme: 'Size', hint: 'Massive' },
    { theme: 'Shape', hint: 'Four legs' },
  ],

  // ==================== Food ====================
  Apple: [
    { theme: 'Purpose', hint: 'Grows on trees' },
    { theme: 'Material', hint: 'Thin skin' },
    { theme: 'Shape', hint: 'Round' },
    { theme: 'Color', hint: 'Bright' },
    { theme: 'Sensory', hint: 'Crunching' },
    { theme: 'Location', hint: 'Kitchen' },
    { theme: 'Size', hint: 'Handheld' },
    { theme: 'Shape', hint: 'Core' },
  ],
  Pizza: [
    { theme: 'Purpose', hint: 'Feeds a group' },
    { theme: 'Material', hint: 'Dough' },
    { theme: 'Shape', hint: 'Round' },
    { theme: 'Color', hint: 'Bright' },
    { theme: 'Sensory', hint: 'Sizzling' },
    { theme: 'Location', hint: 'Kitchen' },
    { theme: 'Size', hint: 'Handheld' },
    { theme: 'Shape', hint: 'Toppings' },
  ],
  Banana: [
    { theme: 'Purpose', hint: 'Grows in bunches' },
    { theme: 'Material', hint: 'Peel' },
    { theme: 'Shape', hint: 'Elongated' },
    { theme: 'Color', hint: 'Bright' },
    { theme: 'Sensory', hint: 'Soft' },
    { theme: 'Location', hint: 'Kitchen' },
    { theme: 'Size', hint: 'Handheld' },
    { theme: 'Shape', hint: 'Curved' },
  ],
  Bread: [
    { theme: 'Purpose', hint: 'Feeds' },
    { theme: 'Material', hint: 'Dough' },
    { theme: 'Shape', hint: 'Layered' },
    { theme: 'Color', hint: 'Pale' },
    { theme: 'Sensory', hint: 'Crunching' },
    { theme: 'Location', hint: 'Kitchen' },
    { theme: 'Size', hint: 'Handheld' },
    { theme: 'Shape', hint: 'Crust' },
  ],
  Butter: [
    { theme: 'Purpose', hint: 'Spreads' },
    { theme: 'Material', hint: 'Fat' },
    { theme: 'Shape', hint: 'Compact' },
    { theme: 'Color', hint: 'Pale' },
    { theme: 'Sensory', hint: 'Melting' },
    { theme: 'Location', hint: 'Kitchen' },
    { theme: 'Size', hint: 'Handheld' },
    { theme: 'Sensory', hint: 'Smooth' },
  ],
  Milk: [
    { theme: 'Purpose', hint: 'Nourishes' },
    { theme: 'Material', hint: 'Liquid' },
    { theme: 'Shape', hint: 'Smooth' },
    { theme: 'Color', hint: 'Pale' },
    { theme: 'Sensory', hint: 'Pouring' },
    { theme: 'Location', hint: 'Kitchen' },
    { theme: 'Size', hint: 'Handheld' },
    { theme: 'Sensory', hint: 'Foam' },
  ],
  Coffee: [
    { theme: 'Purpose', hint: 'Energizes' },
    { theme: 'Material', hint: 'Liquid' },
    { theme: 'Shape', hint: 'Smooth' },
    { theme: 'Color', hint: 'Dark' },
    { theme: 'Sensory', hint: 'Brewing' },
    { theme: 'Location', hint: 'Kitchen' },
    { theme: 'Size', hint: 'Handheld' },
    { theme: 'Sensory', hint: 'Steam' },
  ],
  Orange: [
    { theme: 'Purpose', hint: 'Grows on trees' },
    { theme: 'Material', hint: 'Peel' },
    { theme: 'Shape', hint: 'Round' },
    { theme: 'Color', hint: 'Bright' },
    { theme: 'Sensory', hint: 'Tangy' },
    { theme: 'Location', hint: 'Kitchen' },
    { theme: 'Size', hint: 'Handheld' },
    { theme: 'Shape', hint: 'Zest' },
  ],
  Honey: [
    { theme: 'Purpose', hint: 'Sweetens' },
    { theme: 'Material', hint: 'Liquid' },
    { theme: 'Shape', hint: 'Smooth' },
    { theme: 'Color', hint: 'Bright' },
    { theme: 'Sensory', hint: 'Dripping' },
    { theme: 'Location', hint: 'Kitchen' },
    { theme: 'Size', hint: 'Handheld' },
    { theme: 'Sensory', hint: 'Thick' },
  ],
  Soup: [
    { theme: 'Purpose', hint: 'Nourishes' },
    { theme: 'Material', hint: 'Liquid' },
    { theme: 'Shape', hint: 'Chunky' },
    { theme: 'Color', hint: 'Muted' },
    { theme: 'Sensory', hint: 'Steaming' },
    { theme: 'Location', hint: 'Kitchen' },
    { theme: 'Size', hint: 'Handheld' },
    { theme: 'Sensory', hint: 'Simmering' },
  ],
  Cake: [
    { theme: 'Purpose', hint: 'Celebrates' },
    { theme: 'Material', hint: 'Dough' },
    { theme: 'Shape', hint: 'Layered' },
    { theme: 'Color', hint: 'Bright' },
    { theme: 'Sensory', hint: 'Soft' },
    { theme: 'Location', hint: 'Kitchen' },
    { theme: 'Size', hint: 'Handheld' },
    { theme: 'Shape', hint: 'Frosting' },
  ],
  Egg: [
    { theme: 'Purpose', hint: 'Nourishes' },
    { theme: 'Material', hint: 'Shell' },
    { theme: 'Shape', hint: 'Round' },
    { theme: 'Color', hint: 'Pale' },
    { theme: 'Sensory', hint: 'Cracking' },
    { theme: 'Location', hint: 'Kitchen' },
    { theme: 'Size', hint: 'Handheld' },
    { theme: 'Shape', hint: 'Yolk' },
  ],
  Rice: [
    { theme: 'Purpose', hint: 'Feeds' },
    { theme: 'Material', hint: 'Grain' },
    { theme: 'Shape', hint: 'Compact' },
    { theme: 'Color', hint: 'Pale' },
    { theme: 'Sensory', hint: 'Steaming' },
    { theme: 'Location', hint: 'Kitchen' },
    { theme: 'Size', hint: 'Handheld' },
    { theme: 'Sensory', hint: 'Sticky' },
  ],
  Pasta: [
    { theme: 'Purpose', hint: 'Feeds' },
    { theme: 'Material', hint: 'Dough' },
    { theme: 'Shape', hint: 'Elongated' },
    { theme: 'Color', hint: 'Pale' },
    { theme: 'Sensory', hint: 'Boiling' },
    { theme: 'Location', hint: 'Kitchen' },
    { theme: 'Size', hint: 'Handheld' },
    { theme: 'Shape', hint: 'Twirled' },
  ],
  Steak: [
    { theme: 'Purpose', hint: 'Feeds' },
    { theme: 'Material', hint: 'Meat' },
    { theme: 'Shape', hint: 'Chunky' },
    { theme: 'Color', hint: 'Dark' },
    { theme: 'Sensory', hint: 'Sizzling' },
    { theme: 'Location', hint: 'Kitchen' },
    { theme: 'Size', hint: 'Handheld' },
    { theme: 'Sensory', hint: 'Seared' },
  ],
  Salad: [
    { theme: 'Purpose', hint: 'Nourishes' },
    { theme: 'Material', hint: 'Leaves' },
    { theme: 'Shape', hint: 'Chunky' },
    { theme: 'Color', hint: 'Bright' },
    { theme: 'Sensory', hint: 'Crunching' },
    { theme: 'Location', hint: 'Kitchen' },
    { theme: 'Size', hint: 'Handheld' },
    { theme: 'Sensory', hint: 'Tossed' },
  ],
  Chocolate: [
    { theme: 'Purpose', hint: 'Comforts' },
    { theme: 'Material', hint: 'Cocoa' },
    { theme: 'Shape', hint: 'Compact' },
    { theme: 'Color', hint: 'Dark' },
    { theme: 'Sensory', hint: 'Melting' },
    { theme: 'Location', hint: 'Kitchen' },
    { theme: 'Size', hint: 'Handheld' },
    { theme: 'Sensory', hint: 'Smooth' },
  ],
  Lemon: [
    { theme: 'Purpose', hint: 'Grows on trees' },
    { theme: 'Material', hint: 'Peel' },
    { theme: 'Shape', hint: 'Round' },
    { theme: 'Color', hint: 'Bright' },
    { theme: 'Sensory', hint: 'Tangy' },
    { theme: 'Location', hint: 'Kitchen' },
    { theme: 'Size', hint: 'Handheld' },
    { theme: 'Shape', hint: 'Zest' },
  ],
  Strawberry: [
    { theme: 'Purpose', hint: 'Grows on vines' },
    { theme: 'Material', hint: 'Thin skin' },
    { theme: 'Shape', hint: 'Compact' },
    { theme: 'Color', hint: 'Bright' },
    { theme: 'Sensory', hint: 'Fragrant' },
    { theme: 'Location', hint: 'Kitchen' },
    { theme: 'Size', hint: 'Handheld' },
    { theme: 'Shape', hint: 'Seeds' },
  ],
  Popcorn: [
    { theme: 'Purpose', hint: 'Pops' },
    { theme: 'Material', hint: 'Kernel' },
    { theme: 'Shape', hint: 'Compact' },
    { theme: 'Color', hint: 'Pale' },
    { theme: 'Sensory', hint: 'Crunching' },
    { theme: 'Location', hint: 'Household' },
    { theme: 'Size', hint: 'Handheld' },
    { theme: 'Sensory', hint: 'Fluffy' },
  ],
  Burger: [
    { theme: 'Purpose', hint: 'Feeds' },
    { theme: 'Material', hint: 'Bun' },
    { theme: 'Shape', hint: 'Layered' },
    { theme: 'Color', hint: 'Dark' },
    { theme: 'Sensory', hint: 'Sizzling' },
    { theme: 'Location', hint: 'Household' },
    { theme: 'Size', hint: 'Handheld' },
    { theme: 'Shape', hint: 'Stacked' },
  ],
  'Ice Cream': [
    { theme: 'Purpose', hint: 'Comforts' },
    { theme: 'Material', hint: 'Cream' },
    { theme: 'Shape', hint: 'Smooth' },
    { theme: 'Color', hint: 'Pale' },
    { theme: 'Sensory', hint: 'Melting' },
    { theme: 'Location', hint: 'Household' },
    { theme: 'Size', hint: 'Handheld' },
    { theme: 'Sensory', hint: 'Frozen' },
  ],
  Garlic: [
    { theme: 'Purpose', hint: 'Flavors dishes' },
    { theme: 'Material', hint: 'Cloves' },
    { theme: 'Shape', hint: 'Compact' },
    { theme: 'Color', hint: 'Pale' },
    { theme: 'Sensory', hint: 'Fragrant' },
    { theme: 'Location', hint: 'Kitchen' },
    { theme: 'Size', hint: 'Handheld' },
    { theme: 'Sensory', hint: 'Pungent' },
  ],
  Mushroom: [
    { theme: 'Purpose', hint: 'Grows in shade' },
    { theme: 'Material', hint: 'Cap' },
    { theme: 'Shape', hint: 'Round' },
    { theme: 'Color', hint: 'Neutral' },
    { theme: 'Sensory', hint: 'Fragrant' },
    { theme: 'Location', hint: 'Wilderness' },
    { theme: 'Size', hint: 'Handheld' },
    { theme: 'Sensory', hint: 'Earthy' },
  ],
  Sushi: [
    { theme: 'Purpose', hint: 'Feeds' },
    { theme: 'Material', hint: 'Wrapped' },
    { theme: 'Shape', hint: 'Compact' },
    { theme: 'Color', hint: 'Bright' },
    { theme: 'Sensory', hint: 'Fragrant' },
    { theme: 'Location', hint: 'Kitchen' },
    { theme: 'Size', hint: 'Handheld' },
    { theme: 'Size', hint: 'Bite-sized' },
  ],

  // ==================== Object ====================
  Chair: [
    { theme: 'Purpose', hint: 'Seats' },
    { theme: 'Material', hint: 'Wood' },
    { theme: 'Shape', hint: 'Four legs' },
    { theme: 'Color', hint: 'Neutral' },
    { theme: 'Sensory', hint: 'Creaking' },
    { theme: 'Location', hint: 'Indoor' },
    { theme: 'Size', hint: 'Human-sized' },
    { theme: 'Purpose', hint: 'Stackable' },
  ],
  Bottle: [
    { theme: 'Purpose', hint: 'Stores liquid' },
    { theme: 'Material', hint: 'Glass' },
    { theme: 'Shape', hint: 'Round' },
    { theme: 'Color', hint: 'Clear' },
    { theme: 'Sensory', hint: 'Clinking' },
    { theme: 'Location', hint: 'Kitchen' },
    { theme: 'Size', hint: 'Handheld' },
    { theme: 'Shape', hint: 'Narrow neck' },
  ],
  Pillow: [
    { theme: 'Purpose', hint: 'Comforts' },
    { theme: 'Material', hint: 'Fabric' },
    { theme: 'Shape', hint: 'Compact' },
    { theme: 'Color', hint: 'Pale' },
    { theme: 'Sensory', hint: 'Fluffy' },
    { theme: 'Location', hint: 'Household' },
    { theme: 'Size', hint: 'Human-sized' },
    { theme: 'Sensory', hint: 'Plump' },
  ],
  Key: [
    { theme: 'Purpose', hint: 'Unlocks' },
    { theme: 'Material', hint: 'Metal' },
    { theme: 'Shape', hint: 'Angular' },
    { theme: 'Color', hint: 'Neutral' },
    { theme: 'Sensory', hint: 'Clinking' },
    { theme: 'Location', hint: 'Household' },
    { theme: 'Size', hint: 'Tiny' },
    { theme: 'Shape', hint: 'Teeth' },
  ],
  Fork: [
    { theme: 'Purpose', hint: 'Pierces food' },
    { theme: 'Material', hint: 'Metal' },
    { theme: 'Shape', hint: 'Angular' },
    { theme: 'Color', hint: 'Neutral' },
    { theme: 'Sensory', hint: 'Clinking' },
    { theme: 'Location', hint: 'Kitchen' },
    { theme: 'Size', hint: 'Handheld' },
    { theme: 'Shape', hint: 'Prongs' },
  ],
  Candle: [
    { theme: 'Purpose', hint: 'Illuminates' },
    { theme: 'Material', hint: 'Wax' },
    { theme: 'Shape', hint: 'Elongated' },
    { theme: 'Color', hint: 'Pale' },
    { theme: 'Sensory', hint: 'Flickering' },
    { theme: 'Location', hint: 'Household' },
    { theme: 'Size', hint: 'Handheld' },
    { theme: 'Sensory', hint: 'Melting' },
  ],
  Sock: [
    { theme: 'Purpose', hint: 'Warms feet' },
    { theme: 'Material', hint: 'Fabric' },
    { theme: 'Shape', hint: 'Fitted' },
    { theme: 'Color', hint: 'Neutral' },
    { theme: 'Sensory', hint: 'Soft' },
    { theme: 'Location', hint: 'Closet' },
    { theme: 'Size', hint: 'Small' },
    { theme: 'Sensory', hint: 'Stretchy' },
  ],
  Mirror: [
    { theme: 'Purpose', hint: 'Reflects' },
    { theme: 'Material', hint: 'Glass' },
    { theme: 'Shape', hint: 'Flat' },
    { theme: 'Color', hint: 'Clear' },
    { theme: 'Sensory', hint: 'Gleaming' },
    { theme: 'Location', hint: 'Household' },
    { theme: 'Size', hint: 'Human-sized' },
    { theme: 'Shape', hint: 'Framed' },
  ],
  Knife: [
    { theme: 'Purpose', hint: 'Cuts' },
    { theme: 'Material', hint: 'Metal' },
    { theme: 'Shape', hint: 'Elongated' },
    { theme: 'Color', hint: 'Neutral' },
    { theme: 'Sensory', hint: 'Clinking' },
    { theme: 'Location', hint: 'Kitchen' },
    { theme: 'Size', hint: 'Handheld' },
    { theme: 'Shape', hint: 'Sharp edge' },
  ],
  Bag: [
    { theme: 'Purpose', hint: 'Stores items' },
    { theme: 'Material', hint: 'Fabric' },
    { theme: 'Shape', hint: 'Compact' },
    { theme: 'Color', hint: 'Dark' },
    { theme: 'Sensory', hint: 'Rustling' },
    { theme: 'Location', hint: 'Closet' },
    { theme: 'Size', hint: 'Human-sized' },
    { theme: 'Shape', hint: 'Straps' },
  ],
  Clock: [
    { theme: 'Purpose', hint: 'Ticks' },
    { theme: 'Material', hint: 'Metal' },
    { theme: 'Shape', hint: 'Round' },
    { theme: 'Color', hint: 'Neutral' },
    { theme: 'Sensory', hint: 'Chiming' },
    { theme: 'Location', hint: 'Household' },
    { theme: 'Size', hint: 'Human-sized' },
    { theme: 'Shape', hint: 'Hands' },
  ],
  Book: [
    { theme: 'Purpose', hint: 'Educates' },
    { theme: 'Material', hint: 'Paper' },
    { theme: 'Shape', hint: 'Layered' },
    { theme: 'Color', hint: 'Pale' },
    { theme: 'Sensory', hint: 'Rustling' },
    { theme: 'Location', hint: 'Household' },
    { theme: 'Size', hint: 'Handheld' },
    { theme: 'Shape', hint: 'Pages' },
  ],
  Pen: [
    { theme: 'Purpose', hint: 'Writes' },
    { theme: 'Material', hint: 'Metal' },
    { theme: 'Shape', hint: 'Elongated' },
    { theme: 'Color', hint: 'Dark' },
    { theme: 'Sensory', hint: 'Scratching' },
    { theme: 'Location', hint: 'Household' },
    { theme: 'Size', hint: 'Tiny' },
    { theme: 'Material', hint: 'Ink' },
  ],
  Soap: [
    { theme: 'Purpose', hint: 'Cleanses' },
    { theme: 'Material', hint: 'Soft' },
    { theme: 'Shape', hint: 'Compact' },
    { theme: 'Color', hint: 'Pale' },
    { theme: 'Sensory', hint: 'Fragrant' },
    { theme: 'Location', hint: 'Household' },
    { theme: 'Size', hint: 'Handheld' },
    { theme: 'Sensory', hint: 'Lathering' },
  ],
  Blanket: [
    { theme: 'Purpose', hint: 'Comforts' },
    { theme: 'Material', hint: 'Fabric' },
    { theme: 'Shape', hint: 'Spacious' },
    { theme: 'Color', hint: 'Muted' },
    { theme: 'Sensory', hint: 'Warm' },
    { theme: 'Location', hint: 'Household' },
    { theme: 'Size', hint: 'Human-sized' },
    { theme: 'Material', hint: 'Woven' },
  ],
  Phone: [
    { theme: 'Purpose', hint: 'Connects people' },
    { theme: 'Material', hint: 'Glass' },
    { theme: 'Shape', hint: 'Flat' },
    { theme: 'Color', hint: 'Dark' },
    { theme: 'Sensory', hint: 'Buzzing' },
    { theme: 'Location', hint: 'Household' },
    { theme: 'Size', hint: 'Handheld' },
    { theme: 'Shape', hint: 'Screen' },
  ],
  Lamp: [
    { theme: 'Purpose', hint: 'Illuminates' },
    { theme: 'Material', hint: 'Metal' },
    { theme: 'Shape', hint: 'Angular' },
    { theme: 'Color', hint: 'Bright' },
    { theme: 'Sensory', hint: 'Glowing' },
    { theme: 'Location', hint: 'Indoor' },
    { theme: 'Size', hint: 'Human-sized' },
    { theme: 'Shape', hint: 'Switch' },
  ],
  Stairs: [
    { theme: 'Purpose', hint: 'Connects floors' },
    { theme: 'Material', hint: 'Built' },
    { theme: 'Shape', hint: 'Angular' },
    { theme: 'Color', hint: 'Neutral' },
    { theme: 'Sensory', hint: 'Creaking' },
    { theme: 'Location', hint: 'Indoor' },
    { theme: 'Size', hint: 'Large' },
    { theme: 'Shape', hint: 'Steps' },
  ],
  Cup: [
    { theme: 'Purpose', hint: 'Stores liquid' },
    { theme: 'Material', hint: 'Glass' },
    { theme: 'Shape', hint: 'Round' },
    { theme: 'Color', hint: 'Clear' },
    { theme: 'Sensory', hint: 'Clinking' },
    { theme: 'Location', hint: 'Kitchen' },
    { theme: 'Size', hint: 'Handheld' },
    { theme: 'Shape', hint: 'Handle' },
  ],
  Box: [
    { theme: 'Purpose', hint: 'Stores items' },
    { theme: 'Material', hint: 'Cardboard' },
    { theme: 'Shape', hint: 'Angular' },
    { theme: 'Color', hint: 'Neutral' },
    { theme: 'Sensory', hint: 'Rustling' },
    { theme: 'Location', hint: 'Household' },
    { theme: 'Size', hint: 'Human-sized' },
    { theme: 'Shape', hint: 'Flaps' },
  ],

  // ==================== Nature ====================
  Rain: [
    { theme: 'Purpose', hint: 'Nourishes' },
    { theme: 'Material', hint: 'Water' },
    { theme: 'Shape', hint: 'Scattered' },
    { theme: 'Color', hint: 'Clear' },
    { theme: 'Sensory', hint: 'Pattering' },
    { theme: 'Location', hint: 'Outdoors' },
    { theme: 'Size', hint: 'Large-scale' },
    { theme: 'Shape', hint: 'Puddles' },
  ],
  Sun: [
    { theme: 'Purpose', hint: 'Illuminates' },
    { theme: 'Material', hint: 'Natural' },
    { theme: 'Shape', hint: 'Round' },
    { theme: 'Color', hint: 'Bright' },
    { theme: 'Sensory', hint: 'Warm' },
    { theme: 'Location', hint: 'Sky' },
    { theme: 'Size', hint: 'Massive' },
    { theme: 'Shape', hint: 'Rays' },
  ],
  River: [
    { theme: 'Purpose', hint: 'Flows downhill' },
    { theme: 'Material', hint: 'Water' },
    { theme: 'Shape', hint: 'Elongated' },
    { theme: 'Color', hint: 'Clear' },
    { theme: 'Sensory', hint: 'Splashing' },
    { theme: 'Location', hint: 'Outdoors' },
    { theme: 'Size', hint: 'Large-scale' },
    { theme: 'Shape', hint: 'Banks' },
  ],
  Mountain: [
    { theme: 'Purpose', hint: 'Towers' },
    { theme: 'Material', hint: 'Rock' },
    { theme: 'Shape', hint: 'Angular' },
    { theme: 'Color', hint: 'Muted' },
    { theme: 'Sensory', hint: 'Echoing' },
    { theme: 'Location', hint: 'Outdoors' },
    { theme: 'Size', hint: 'Massive' },
    { theme: 'Shape', hint: 'Peak' },
  ],
  Forest: [
    { theme: 'Purpose', hint: 'Shelters wildlife' },
    { theme: 'Material', hint: 'Trees' },
    { theme: 'Shape', hint: 'Spacious' },
    { theme: 'Color', hint: 'Muted' },
    { theme: 'Sensory', hint: 'Rustling' },
    { theme: 'Location', hint: 'Outdoors' },
    { theme: 'Size', hint: 'Massive' },
    { theme: 'Shape', hint: 'Canopy' },
  ],
  Sand: [
    { theme: 'Purpose', hint: 'Shifts underfoot' },
    { theme: 'Material', hint: 'Grains' },
    { theme: 'Shape', hint: 'Scattered' },
    { theme: 'Color', hint: 'Pale' },
    { theme: 'Sensory', hint: 'Rough' },
    { theme: 'Location', hint: 'Outdoors' },
    { theme: 'Size', hint: 'Large-scale' },
    { theme: 'Sensory', hint: 'Warm' },
  ],
  Cloud: [
    { theme: 'Purpose', hint: 'Drifts' },
    { theme: 'Material', hint: 'Vapor' },
    { theme: 'Shape', hint: 'Round' },
    { theme: 'Color', hint: 'Pale' },
    { theme: 'Sensory', hint: 'Quiet' },
    { theme: 'Location', hint: 'Sky' },
    { theme: 'Size', hint: 'Massive' },
    { theme: 'Sensory', hint: 'Fluffy' },
  ],
  Fire: [
    { theme: 'Purpose', hint: 'Burns' },
    { theme: 'Material', hint: 'Fuel' },
    { theme: 'Shape', hint: 'Flickering' },
    { theme: 'Color', hint: 'Bright' },
    { theme: 'Sensory', hint: 'Crackling' },
    { theme: 'Location', hint: 'Outdoors' },
    { theme: 'Size', hint: 'Large-scale' },
    { theme: 'Shape', hint: 'Smoke' },
  ],
  Cave: [
    { theme: 'Purpose', hint: 'Shelters' },
    { theme: 'Material', hint: 'Rock' },
    { theme: 'Shape', hint: 'Hollow' },
    { theme: 'Color', hint: 'Dark' },
    { theme: 'Sensory', hint: 'Echoing' },
    { theme: 'Location', hint: 'Outdoors' },
    { theme: 'Size', hint: 'Massive' },
    { theme: 'Shape', hint: 'Entrance' },
  ],
  Island: [
    { theme: 'Purpose', hint: 'Isolates' },
    { theme: 'Material', hint: 'Grains' },
    { theme: 'Shape', hint: 'Elongated' },
    { theme: 'Color', hint: 'Muted' },
    { theme: 'Sensory', hint: 'Warm' },
    { theme: 'Location', hint: 'Coastline' },
    { theme: 'Size', hint: 'Massive' },
    { theme: 'Shape', hint: 'Shoreline' },
  ],
  Wind: [
    { theme: 'Purpose', hint: 'Drifts' },
    { theme: 'Material', hint: 'Air' },
    { theme: 'Shape', hint: 'Scattered' },
    { theme: 'Color', hint: 'Clear' },
    { theme: 'Sensory', hint: 'Howling' },
    { theme: 'Location', hint: 'Outdoors' },
    { theme: 'Size', hint: 'Large-scale' },
    { theme: 'Sensory', hint: 'Gusting' },
  ],
  Leaf: [
    { theme: 'Purpose', hint: 'Grows on branches' },
    { theme: 'Material', hint: 'Delicate' },
    { theme: 'Shape', hint: 'Flat' },
    { theme: 'Color', hint: 'Bright' },
    { theme: 'Sensory', hint: 'Rustling' },
    { theme: 'Location', hint: 'Outdoors' },
    { theme: 'Size', hint: 'Small' },
    { theme: 'Shape', hint: 'Veins' },
  ],
  Stone: [
    { theme: 'Purpose', hint: 'Forms over time' },
    { theme: 'Material', hint: 'Mineral' },
    { theme: 'Shape', hint: 'Angular' },
    { theme: 'Color', hint: 'Neutral' },
    { theme: 'Sensory', hint: 'Rough' },
    { theme: 'Location', hint: 'Outdoors' },
    { theme: 'Size', hint: 'Small' },
    { theme: 'Sensory', hint: 'Weathered' },
  ],
  Ice: [
    { theme: 'Purpose', hint: 'Freezes' },
    { theme: 'Material', hint: 'Water' },
    { theme: 'Shape', hint: 'Angular' },
    { theme: 'Color', hint: 'Clear' },
    { theme: 'Sensory', hint: 'Cracking' },
    { theme: 'Location', hint: 'Outdoors' },
    { theme: 'Size', hint: 'Small' },
    { theme: 'Sensory', hint: 'Melting' },
  ],
  Desert: [
    { theme: 'Purpose', hint: 'Isolates' },
    { theme: 'Material', hint: 'Grains' },
    { theme: 'Shape', hint: 'Spacious' },
    { theme: 'Color', hint: 'Pale' },
    { theme: 'Sensory', hint: 'Warm' },
    { theme: 'Location', hint: 'Outdoors' },
    { theme: 'Size', hint: 'Large-scale' },
    { theme: 'Shape', hint: 'Dunes' },
  ],

  // ==================== Vehicle ====================
  Car: [
    { theme: 'Purpose', hint: 'Transports' },
    { theme: 'Material', hint: 'Metal' },
    { theme: 'Shape', hint: 'Elongated' },
    { theme: 'Color', hint: 'Painted' },
    { theme: 'Sensory', hint: 'Rumbling' },
    { theme: 'Location', hint: 'Roadside' },
    { theme: 'Size', hint: 'Multi-person' },
    { theme: 'Shape', hint: 'Wheels' },
  ],
  Bicycle: [
    { theme: 'Purpose', hint: 'Transports' },
    { theme: 'Material', hint: 'Metal' },
    { theme: 'Shape', hint: 'Elongated' },
    { theme: 'Color', hint: 'Painted' },
    { theme: 'Sensory', hint: 'Clicking' },
    { theme: 'Location', hint: 'Roadside' },
    { theme: 'Size', hint: 'Human-sized' },
    { theme: 'Shape', hint: 'Wheels' },
  ],
  Boat: [
    { theme: 'Purpose', hint: 'Transports' },
    { theme: 'Material', hint: 'Wood' },
    { theme: 'Shape', hint: 'Elongated' },
    { theme: 'Color', hint: 'Painted' },
    { theme: 'Sensory', hint: 'Splashing' },
    { theme: 'Location', hint: 'Coastline' },
    { theme: 'Size', hint: 'Multi-person' },
    { theme: 'Shape', hint: 'Hull' },
  ],
  Train: [
    { theme: 'Purpose', hint: 'Transports' },
    { theme: 'Material', hint: 'Metal' },
    { theme: 'Shape', hint: 'Elongated' },
    { theme: 'Color', hint: 'Muted' },
    { theme: 'Sensory', hint: 'Rumbling' },
    { theme: 'Location', hint: 'Tracks' },
    { theme: 'Size', hint: 'Multi-person' },
    { theme: 'Shape', hint: 'Wheels' },
  ],
  Plane: [
    { theme: 'Purpose', hint: 'Transports' },
    { theme: 'Material', hint: 'Metal' },
    { theme: 'Shape', hint: 'Elongated' },
    { theme: 'Color', hint: 'Painted' },
    { theme: 'Sensory', hint: 'Roaring' },
    { theme: 'Location', hint: 'Sky' },
    { theme: 'Size', hint: 'Multi-person' },
    { theme: 'Shape', hint: 'Wings' },
  ],
  Motorbike: [
    { theme: 'Purpose', hint: 'Transports' },
    { theme: 'Material', hint: 'Metal' },
    { theme: 'Shape', hint: 'Elongated' },
    { theme: 'Color', hint: 'Painted' },
    { theme: 'Sensory', hint: 'Roaring' },
    { theme: 'Location', hint: 'Roadside' },
    { theme: 'Size', hint: 'Human-sized' },
    { theme: 'Shape', hint: 'Wheels' },
  ],
  Submarine: [
    { theme: 'Purpose', hint: 'Transports' },
    { theme: 'Material', hint: 'Metal' },
    { theme: 'Shape', hint: 'Elongated' },
    { theme: 'Color', hint: 'Dark' },
    { theme: 'Sensory', hint: 'Humming' },
    { theme: 'Location', hint: 'Underwater' },
    { theme: 'Size', hint: 'Multi-person' },
    { theme: 'Shape', hint: 'Hull' },
  ],

  // ==================== Place ====================
  Beach: [
    { theme: 'Purpose', hint: 'Relaxes visitors' },
    { theme: 'Material', hint: 'Grains' },
    { theme: 'Shape', hint: 'Elongated' },
    { theme: 'Color', hint: 'Pale' },
    { theme: 'Sensory', hint: 'Breezy' },
    { theme: 'Location', hint: 'Coastline' },
    { theme: 'Size', hint: 'Large' },
    { theme: 'Shape', hint: 'Waves' },
  ],
  Market: [
    { theme: 'Purpose', hint: 'Trades goods' },
    { theme: 'Material', hint: 'Built' },
    { theme: 'Shape', hint: 'Spacious' },
    { theme: 'Color', hint: 'Bright' },
    { theme: 'Sensory', hint: 'Chattering' },
    { theme: 'Location', hint: 'Public' },
    { theme: 'Size', hint: 'Large' },
    { theme: 'Shape', hint: 'Stalls' },
  ],
  Hospital: [
    { theme: 'Purpose', hint: 'Heals' },
    { theme: 'Material', hint: 'Built' },
    { theme: 'Shape', hint: 'Spacious' },
    { theme: 'Color', hint: 'Pale' },
    { theme: 'Sensory', hint: 'Beeping' },
    { theme: 'Location', hint: 'Public' },
    { theme: 'Size', hint: 'Large' },
    { theme: 'Shape', hint: 'Wards' },
  ],
  School: [
    { theme: 'Purpose', hint: 'Educates' },
    { theme: 'Material', hint: 'Built' },
    { theme: 'Shape', hint: 'Spacious' },
    { theme: 'Color', hint: 'Muted' },
    { theme: 'Sensory', hint: 'Chattering' },
    { theme: 'Location', hint: 'Public' },
    { theme: 'Size', hint: 'Large' },
    { theme: 'Shape', hint: 'Classrooms' },
  ],
  Restaurant: [
    { theme: 'Purpose', hint: 'Feeds' },
    { theme: 'Material', hint: 'Built' },
    { theme: 'Shape', hint: 'Spacious' },
    { theme: 'Color', hint: 'Muted' },
    { theme: 'Sensory', hint: 'Sizzling' },
    { theme: 'Location', hint: 'Public' },
    { theme: 'Size', hint: 'Large' },
    { theme: 'Shape', hint: 'Tables' },
  ],
  Park: [
    { theme: 'Purpose', hint: 'Relaxes visitors' },
    { theme: 'Material', hint: 'Natural' },
    { theme: 'Shape', hint: 'Spacious' },
    { theme: 'Color', hint: 'Bright' },
    { theme: 'Sensory', hint: 'Chirping' },
    { theme: 'Location', hint: 'Public' },
    { theme: 'Size', hint: 'Large' },
    { theme: 'Shape', hint: 'Paths' },
  ],
  Church: [
    { theme: 'Purpose', hint: 'Gathers a community' },
    { theme: 'Material', hint: 'Built' },
    { theme: 'Shape', hint: 'Spacious' },
    { theme: 'Color', hint: 'Muted' },
    { theme: 'Sensory', hint: 'Echoing' },
    { theme: 'Location', hint: 'Public' },
    { theme: 'Size', hint: 'Large' },
    { theme: 'Shape', hint: 'Pews' },
  ],

  // ==================== Clothing ====================
  Hat: [
    { theme: 'Purpose', hint: 'Shields the head' },
    { theme: 'Material', hint: 'Fabric' },
    { theme: 'Shape', hint: 'Round' },
    { theme: 'Color', hint: 'Bright' },
    { theme: 'Sensory', hint: 'Soft' },
    { theme: 'Location', hint: 'Closet' },
    { theme: 'Size', hint: 'Small' },
    { theme: 'Shape', hint: 'Brim' },
  ],
  Jacket: [
    { theme: 'Purpose', hint: 'Shields from cold' },
    { theme: 'Material', hint: 'Fabric' },
    { theme: 'Shape', hint: 'Fitted' },
    { theme: 'Color', hint: 'Muted' },
    { theme: 'Sensory', hint: 'Warm' },
    { theme: 'Location', hint: 'Closet' },
    { theme: 'Size', hint: 'Body-sized' },
    { theme: 'Shape', hint: 'Zipper' },
  ],
  Dress: [
    { theme: 'Purpose', hint: 'Adorns' },
    { theme: 'Material', hint: 'Fabric' },
    { theme: 'Shape', hint: 'Fitted' },
    { theme: 'Color', hint: 'Bright' },
    { theme: 'Sensory', hint: 'Soft' },
    { theme: 'Location', hint: 'Closet' },
    { theme: 'Size', hint: 'Body-sized' },
    { theme: 'Shape', hint: 'Hem' },
  ],
  Boots: [
    { theme: 'Purpose', hint: 'Shields the feet' },
    { theme: 'Material', hint: 'Leather' },
    { theme: 'Shape', hint: 'Fitted' },
    { theme: 'Color', hint: 'Dark' },
    { theme: 'Sensory', hint: 'Rough' },
    { theme: 'Location', hint: 'Closet' },
    { theme: 'Size', hint: 'Body-sized' },
    { theme: 'Shape', hint: 'Laces' },
  ],
  Scarf: [
    { theme: 'Purpose', hint: 'Shields the neck' },
    { theme: 'Material', hint: 'Fabric' },
    { theme: 'Shape', hint: 'Elongated' },
    { theme: 'Color', hint: 'Muted' },
    { theme: 'Sensory', hint: 'Warm' },
    { theme: 'Location', hint: 'Closet' },
    { theme: 'Size', hint: 'Body-sized' },
    { theme: 'Sensory', hint: 'Wrapped' },
  ],
};
