// Reverse mode hint content — see docs/reverse-hint-content-guidelines.md
// for the rules this data follows (7 themes x 2 values = 14 hints/word,
// freshness target for a 7-player/7-cycle game).
//
// PILOT — 3 words only, for style review before authoring the full 99.
export const REVERSE_HINTS = {
  Dog: [
    { theme: 'Purpose', hint: 'Guard' },
    { theme: 'Purpose', hint: 'Fetch' },
    { theme: 'Material', hint: 'Fur' },
    { theme: 'Material', hint: 'Paws' },
    { theme: 'Shape', hint: 'Tail' },
    { theme: 'Shape', hint: 'Snout' },
    { theme: 'Color', hint: 'Spotted' },
    { theme: 'Color', hint: 'Golden' },
    { theme: 'Sensory', hint: 'Bark' },
    { theme: 'Sensory', hint: 'Wet nose' },
    { theme: 'Location', hint: 'Kennel' },
    { theme: 'Location', hint: 'Leash' },
    { theme: 'Size', hint: 'Knee-high' },
    { theme: 'Size', hint: 'Breeds vary' },
  ],
  Boat: [
    { theme: 'Purpose', hint: 'Crossing' },
    { theme: 'Purpose', hint: 'Fishing' },
    { theme: 'Material', hint: 'Wood' },
    { theme: 'Material', hint: 'Hull' },
    { theme: 'Shape', hint: 'Hollow' },
    { theme: 'Shape', hint: 'Pointed bow' },
    { theme: 'Color', hint: 'White' },
    { theme: 'Color', hint: 'Painted' },
    { theme: 'Sensory', hint: 'Splashing' },
    { theme: 'Sensory', hint: 'Rocking' },
    { theme: 'Location', hint: 'Harbor' },
    { theme: 'Location', hint: 'Dock' },
    { theme: 'Size', hint: 'One-person' },
    { theme: 'Size', hint: 'Fits a crew' },
  ],
  Chair: [
    { theme: 'Purpose', hint: 'Sitting' },
    { theme: 'Purpose', hint: 'Resting' },
    { theme: 'Material', hint: 'Wooden' },
    { theme: 'Material', hint: 'Cushioned' },
    { theme: 'Shape', hint: 'Four legs' },
    { theme: 'Shape', hint: 'Backrest' },
    { theme: 'Color', hint: 'Matches table' },
    { theme: 'Color', hint: 'Painted wood' },
    { theme: 'Sensory', hint: 'Creaky' },
    { theme: 'Sensory', hint: 'Firm' },
    { theme: 'Location', hint: 'Kitchen' },
    { theme: 'Location', hint: 'Office' },
    { theme: 'Size', hint: 'One person' },
    { theme: 'Size', hint: 'Stackable' },
  ],
};
