// Reverse mode hint content — see docs/reverse-hint-content-guidelines.md
// for the rules this data follows (Broadness Principle, 8 hints/word,
// cross-word reuse encouraged, no duplicate within one word).
//
// Full 99/99 word coverage. Keys must match a words.js entry's w[0] exactly
// (secretWord in game.js) — Batch 1's original "Cheese" was fixed to
// "Butter" here since Cheese only ever appears as w[1], never w[0], so it
// could never actually be picked as a secret word.
export const REVERSE_HINTS = {
  // ==================== Animal ====================
  Dog: [
    { theme: 'Purpose', hint: 'Companion' },
    { theme: 'Material', hint: 'Soft' },
    { theme: 'Shape', hint: 'Compact' },
    { theme: 'Color', hint: 'Brown' },
    { theme: 'Sensory', hint: 'Warm' },
    { theme: 'Location', hint: 'Household' },
    { theme: 'Size', hint: 'Small-to-medium' },
    { theme: 'Sensory', hint: 'Loud' },
  ],
  Cat: [
    { theme: 'Purpose', hint: 'Companion' },
    { theme: 'Material', hint: 'Soft' },
    { theme: 'Shape', hint: 'Compact' },
    { theme: 'Color', hint: 'Neutral' },
    { theme: 'Sensory', hint: 'Quiet' },
    { theme: 'Location', hint: 'Household' },
    { theme: 'Size', hint: 'Small-to-medium' },
    { theme: 'Sensory', hint: 'Warm' },
  ],
  Frog: [
    { theme: 'Purpose', hint: 'Agile' },
    { theme: 'Material', hint: 'Soft' },
    { theme: 'Shape', hint: 'Compact' },
    { theme: 'Color', hint: 'Neutral' },
    { theme: 'Sensory', hint: 'Cool' },
    { theme: 'Location', hint: 'Outdoors' },
    { theme: 'Size', hint: 'Small-to-medium' },
    { theme: 'Sensory', hint: 'Loud' },
  ],
  Shark: [
    { theme: 'Purpose', hint: 'Hunts' },
    { theme: 'Material', hint: 'Sturdy' },
    { theme: 'Shape', hint: 'Elongated' },
    { theme: 'Color', hint: 'Dark' },
    { theme: 'Sensory', hint: 'Cold' },
    { theme: 'Location', hint: 'Outdoors' },
    { theme: 'Size', hint: 'Large' },
    { theme: 'Shape', hint: 'Angular' },
  ],
  Chicken: [
    { theme: 'Purpose', hint: 'Nourishing' },
    { theme: 'Material', hint: 'Soft' },
    { theme: 'Shape', hint: 'Compact' },
    { theme: 'Color', hint: 'Pale' },
    { theme: 'Sensory', hint: 'Loud' },
    { theme: 'Location', hint: 'Rural' },
    { theme: 'Size', hint: 'Small-to-medium' },
    { theme: 'Purpose', hint: 'Communal' },
  ],
  Horse: [
    { theme: 'Purpose', hint: 'Carries' },
    { theme: 'Material', hint: 'Sturdy' },
    { theme: 'Shape', hint: 'Elongated' },
    { theme: 'Color', hint: 'Brown' },
    { theme: 'Sensory', hint: 'Loud' },
    { theme: 'Location', hint: 'Outdoors' },
    { theme: 'Size', hint: 'Large' },
    { theme: 'Location', hint: 'Rural' },
  ],
  Cow: [
    { theme: 'Purpose', hint: 'Nourishing' },
    { theme: 'Material', hint: 'Sturdy' },
    { theme: 'Shape', hint: 'Bulky' },
    { theme: 'Color', hint: 'Neutral' },
    { theme: 'Sensory', hint: 'Loud' },
    { theme: 'Location', hint: 'Rural' },
    { theme: 'Size', hint: 'Large' },
    { theme: 'Purpose', hint: 'Communal' },
  ],
  Rabbit: [
    { theme: 'Purpose', hint: 'Companion' },
    { theme: 'Material', hint: 'Soft' },
    { theme: 'Shape', hint: 'Compact' },
    { theme: 'Color', hint: 'Pale' },
    { theme: 'Sensory', hint: 'Quiet' },
    { theme: 'Location', hint: 'Household' },
    { theme: 'Size', hint: 'Small-to-medium' },
    { theme: 'Sensory', hint: 'Warm' },
  ],
  Bee: [
    { theme: 'Purpose', hint: 'Pollinates' },
    { theme: 'Material', hint: 'Delicate' },
    { theme: 'Shape', hint: 'Compact' },
    { theme: 'Color', hint: 'Bright' },
    { theme: 'Sensory', hint: 'Loud' },
    { theme: 'Location', hint: 'Outdoors' },
    { theme: 'Size', hint: 'Tiny' },
    { theme: 'Purpose', hint: 'Communal' },
  ],
  Owl: [
    { theme: 'Purpose', hint: 'Hunts' },
    { theme: 'Material', hint: 'Soft' },
    { theme: 'Shape', hint: 'Compact' },
    { theme: 'Color', hint: 'Neutral' },
    { theme: 'Sensory', hint: 'Quiet' },
    { theme: 'Location', hint: 'Outdoors' },
    { theme: 'Size', hint: 'Small-to-medium' },
    { theme: 'Sensory', hint: 'Loud' },
  ],
  Pig: [
    { theme: 'Purpose', hint: 'Nourishing' },
    { theme: 'Material', hint: 'Soft' },
    { theme: 'Shape', hint: 'Bulky' },
    { theme: 'Color', hint: 'Pale' },
    { theme: 'Sensory', hint: 'Loud' },
    { theme: 'Location', hint: 'Rural' },
    { theme: 'Size', hint: 'Small-to-medium' },
    { theme: 'Purpose', hint: 'Communal' },
  ],
  Snake: [
    { theme: 'Purpose', hint: 'Hunts' },
    { theme: 'Material', hint: 'Smooth' },
    { theme: 'Shape', hint: 'Elongated' },
    { theme: 'Color', hint: 'Neutral' },
    { theme: 'Sensory', hint: 'Quiet' },
    { theme: 'Location', hint: 'Outdoors' },
    { theme: 'Size', hint: 'Small-to-medium' },
    { theme: 'Shape', hint: 'Curved' },
  ],
  Crab: [
    { theme: 'Purpose', hint: 'Nourishing' },
    { theme: 'Material', hint: 'Hard' },
    { theme: 'Shape', hint: 'Compact' },
    { theme: 'Color', hint: 'Neutral' },
    { theme: 'Sensory', hint: 'Rough' },
    { theme: 'Location', hint: 'Outdoors' },
    { theme: 'Size', hint: 'Small-to-medium' },
    { theme: 'Shape', hint: 'Angular' },
  ],
  Elephant: [
    { theme: 'Purpose', hint: 'Carries' },
    { theme: 'Material', hint: 'Sturdy' },
    { theme: 'Shape', hint: 'Bulky' },
    { theme: 'Color', hint: 'Neutral' },
    { theme: 'Sensory', hint: 'Loud' },
    { theme: 'Location', hint: 'Outdoors' },
    { theme: 'Size', hint: 'Large' },
    { theme: 'Purpose', hint: 'Communal' },
  ],
  Lion: [
    { theme: 'Purpose', hint: 'Hunts' },
    { theme: 'Material', hint: 'Soft' },
    { theme: 'Shape', hint: 'Bulky' },
    { theme: 'Color', hint: 'Brown' },
    { theme: 'Sensory', hint: 'Loud' },
    { theme: 'Location', hint: 'Outdoors' },
    { theme: 'Size', hint: 'Large' },
    { theme: 'Purpose', hint: 'Communal' },
  ],
  Penguin: [
    { theme: 'Purpose', hint: 'Agile' },
    { theme: 'Material', hint: 'Soft' },
    { theme: 'Shape', hint: 'Compact' },
    { theme: 'Color', hint: 'Dark' },
    { theme: 'Sensory', hint: 'Cold' },
    { theme: 'Location', hint: 'Outdoors' },
    { theme: 'Size', hint: 'Small-to-medium' },
    { theme: 'Sensory', hint: 'Loud' },
  ],
  Spider: [
    { theme: 'Purpose', hint: 'Hunts' },
    { theme: 'Material', hint: 'Delicate' },
    { theme: 'Shape', hint: 'Compact' },
    { theme: 'Color', hint: 'Dark' },
    { theme: 'Sensory', hint: 'Quiet' },
    { theme: 'Location', hint: 'Household' },
    { theme: 'Size', hint: 'Tiny' },
    { theme: 'Shape', hint: 'Angular' },
  ],
  Parrot: [
    { theme: 'Purpose', hint: 'Companion' },
    { theme: 'Material', hint: 'Soft' },
    { theme: 'Shape', hint: 'Compact' },
    { theme: 'Color', hint: 'Bright' },
    { theme: 'Sensory', hint: 'Loud' },
    { theme: 'Location', hint: 'Household' },
    { theme: 'Size', hint: 'Small-to-medium' },
    { theme: 'Purpose', hint: 'Communal' },
  ],
  Salmon: [
    { theme: 'Purpose', hint: 'Nourishing' },
    { theme: 'Material', hint: 'Smooth' },
    { theme: 'Shape', hint: 'Elongated' },
    { theme: 'Color', hint: 'Bright' },
    { theme: 'Sensory', hint: 'Cool' },
    { theme: 'Location', hint: 'Outdoors' },
    { theme: 'Size', hint: 'Small-to-medium' },
    { theme: 'Shape', hint: 'Curved' },
  ],
  Gorilla: [
    { theme: 'Purpose', hint: 'Protective' },
    { theme: 'Material', hint: 'Soft' },
    { theme: 'Shape', hint: 'Bulky' },
    { theme: 'Color', hint: 'Dark' },
    { theme: 'Sensory', hint: 'Loud' },
    { theme: 'Location', hint: 'Outdoors' },
    { theme: 'Size', hint: 'Large' },
    { theme: 'Purpose', hint: 'Communal' },
  ],

  // ==================== Food ====================
  Apple: [
    { theme: 'Purpose', hint: 'Nourishing' },
    { theme: 'Material', hint: 'Natural' },
    { theme: 'Shape', hint: 'Round' },
    { theme: 'Color', hint: 'Bright' },
    { theme: 'Sensory', hint: 'Crisp' },
    { theme: 'Location', hint: 'Kitchen' },
    { theme: 'Size', hint: 'Handheld' },
    { theme: 'Sensory', hint: 'Fragrant' },
  ],
  Pizza: [
    { theme: 'Purpose', hint: 'Filling' },
    { theme: 'Material', hint: 'Baked' },
    { theme: 'Shape', hint: 'Round' },
    { theme: 'Color', hint: 'Bright' },
    { theme: 'Sensory', hint: 'Fragrant' },
    { theme: 'Location', hint: 'Kitchen' },
    { theme: 'Size', hint: 'Handheld' },
    { theme: 'Purpose', hint: 'Comforting' },
  ],
  Banana: [
    { theme: 'Purpose', hint: 'Nourishing' },
    { theme: 'Material', hint: 'Natural' },
    { theme: 'Shape', hint: 'Elongated' },
    { theme: 'Color', hint: 'Bright' },
    { theme: 'Sensory', hint: 'Soft' },
    { theme: 'Location', hint: 'Kitchen' },
    { theme: 'Size', hint: 'Handheld' },
    { theme: 'Shape', hint: 'Curved' },
  ],
  Bread: [
    { theme: 'Purpose', hint: 'Filling' },
    { theme: 'Material', hint: 'Baked' },
    { theme: 'Shape', hint: 'Layered' },
    { theme: 'Color', hint: 'Pale' },
    { theme: 'Sensory', hint: 'Soft' },
    { theme: 'Location', hint: 'Kitchen' },
    { theme: 'Size', hint: 'Handheld' },
    { theme: 'Sensory', hint: 'Crisp' },
  ],
  Butter: [
    { theme: 'Purpose', hint: 'Spreadable' },
    { theme: 'Material', hint: 'Soft' },
    { theme: 'Shape', hint: 'Compact' },
    { theme: 'Color', hint: 'Pale' },
    { theme: 'Sensory', hint: 'Rich' },
    { theme: 'Location', hint: 'Kitchen' },
    { theme: 'Size', hint: 'Handheld' },
    { theme: 'Material', hint: 'Smooth' },
  ],
  Milk: [
    { theme: 'Purpose', hint: 'Nourishing' },
    { theme: 'Material', hint: 'Liquid' },
    { theme: 'Shape', hint: 'Smooth' },
    { theme: 'Color', hint: 'Pale' },
    { theme: 'Sensory', hint: 'Cool' },
    { theme: 'Location', hint: 'Kitchen' },
    { theme: 'Size', hint: 'Handheld' },
    { theme: 'Purpose', hint: 'Comforting' },
  ],
  Coffee: [
    { theme: 'Purpose', hint: 'Energizing' },
    { theme: 'Material', hint: 'Liquid' },
    { theme: 'Shape', hint: 'Smooth' },
    { theme: 'Color', hint: 'Dark' },
    { theme: 'Sensory', hint: 'Fragrant' },
    { theme: 'Location', hint: 'Kitchen' },
    { theme: 'Size', hint: 'Handheld' },
    { theme: 'Sensory', hint: 'Warm' },
  ],
  Orange: [
    { theme: 'Purpose', hint: 'Nourishing' },
    { theme: 'Material', hint: 'Natural' },
    { theme: 'Shape', hint: 'Round' },
    { theme: 'Color', hint: 'Bright' },
    { theme: 'Sensory', hint: 'Fragrant' },
    { theme: 'Location', hint: 'Kitchen' },
    { theme: 'Size', hint: 'Handheld' },
    { theme: 'Sensory', hint: 'Tangy' },
  ],
  Honey: [
    { theme: 'Purpose', hint: 'Spreadable' },
    { theme: 'Material', hint: 'Liquid' },
    { theme: 'Shape', hint: 'Smooth' },
    { theme: 'Color', hint: 'Bright' },
    { theme: 'Sensory', hint: 'Fragrant' },
    { theme: 'Location', hint: 'Kitchen' },
    { theme: 'Size', hint: 'Handheld' },
    { theme: 'Purpose', hint: 'Comforting' },
  ],
  Soup: [
    { theme: 'Purpose', hint: 'Nourishing' },
    { theme: 'Material', hint: 'Liquid' },
    { theme: 'Shape', hint: 'Chunky' },
    { theme: 'Color', hint: 'Muted' },
    { theme: 'Sensory', hint: 'Warm' },
    { theme: 'Location', hint: 'Kitchen' },
    { theme: 'Size', hint: 'Handheld' },
    { theme: 'Purpose', hint: 'Comforting' },
  ],
  Cake: [
    { theme: 'Purpose', hint: 'Comforting' },
    { theme: 'Material', hint: 'Baked' },
    { theme: 'Shape', hint: 'Layered' },
    { theme: 'Color', hint: 'Bright' },
    { theme: 'Sensory', hint: 'Soft' },
    { theme: 'Location', hint: 'Kitchen' },
    { theme: 'Size', hint: 'Handheld' },
    { theme: 'Purpose', hint: 'Communal' },
  ],
  Egg: [
    { theme: 'Purpose', hint: 'Nourishing' },
    { theme: 'Material', hint: 'Delicate' },
    { theme: 'Shape', hint: 'Round' },
    { theme: 'Color', hint: 'Pale' },
    { theme: 'Sensory', hint: 'Smooth' },
    { theme: 'Location', hint: 'Kitchen' },
    { theme: 'Size', hint: 'Handheld' },
    { theme: 'Shape', hint: 'Compact' },
  ],
  Rice: [
    { theme: 'Purpose', hint: 'Filling' },
    { theme: 'Material', hint: 'Natural' },
    { theme: 'Shape', hint: 'Compact' },
    { theme: 'Color', hint: 'Pale' },
    { theme: 'Sensory', hint: 'Soft' },
    { theme: 'Location', hint: 'Kitchen' },
    { theme: 'Size', hint: 'Handheld' },
    { theme: 'Purpose', hint: 'Comforting' },
  ],
  Pasta: [
    { theme: 'Purpose', hint: 'Filling' },
    { theme: 'Material', hint: 'Smooth' },
    { theme: 'Shape', hint: 'Elongated' },
    { theme: 'Color', hint: 'Pale' },
    { theme: 'Sensory', hint: 'Soft' },
    { theme: 'Location', hint: 'Kitchen' },
    { theme: 'Size', hint: 'Handheld' },
    { theme: 'Purpose', hint: 'Comforting' },
  ],
  Steak: [
    { theme: 'Purpose', hint: 'Filling' },
    { theme: 'Material', hint: 'Rich' },
    { theme: 'Shape', hint: 'Chunky' },
    { theme: 'Color', hint: 'Dark' },
    { theme: 'Sensory', hint: 'Fragrant' },
    { theme: 'Location', hint: 'Kitchen' },
    { theme: 'Size', hint: 'Handheld' },
    { theme: 'Sensory', hint: 'Rough' },
  ],
  Salad: [
    { theme: 'Purpose', hint: 'Nourishing' },
    { theme: 'Material', hint: 'Natural' },
    { theme: 'Shape', hint: 'Chunky' },
    { theme: 'Color', hint: 'Bright' },
    { theme: 'Sensory', hint: 'Crisp' },
    { theme: 'Location', hint: 'Kitchen' },
    { theme: 'Size', hint: 'Handheld' },
    { theme: 'Purpose', hint: 'Refreshing' },
  ],
  Chocolate: [
    { theme: 'Purpose', hint: 'Comforting' },
    { theme: 'Material', hint: 'Rich' },
    { theme: 'Shape', hint: 'Compact' },
    { theme: 'Color', hint: 'Dark' },
    { theme: 'Sensory', hint: 'Fragrant' },
    { theme: 'Location', hint: 'Kitchen' },
    { theme: 'Size', hint: 'Handheld' },
    { theme: 'Sensory', hint: 'Smooth' },
  ],
  Lemon: [
    { theme: 'Purpose', hint: 'Nourishing' },
    { theme: 'Material', hint: 'Natural' },
    { theme: 'Shape', hint: 'Round' },
    { theme: 'Color', hint: 'Bright' },
    { theme: 'Sensory', hint: 'Tangy' },
    { theme: 'Location', hint: 'Kitchen' },
    { theme: 'Size', hint: 'Handheld' },
    { theme: 'Sensory', hint: 'Fragrant' },
  ],
  Strawberry: [
    { theme: 'Purpose', hint: 'Nourishing' },
    { theme: 'Material', hint: 'Natural' },
    { theme: 'Shape', hint: 'Compact' },
    { theme: 'Color', hint: 'Bright' },
    { theme: 'Sensory', hint: 'Fragrant' },
    { theme: 'Location', hint: 'Kitchen' },
    { theme: 'Size', hint: 'Handheld' },
    { theme: 'Sensory', hint: 'Soft' },
  ],
  Popcorn: [
    { theme: 'Purpose', hint: 'Snackable' },
    { theme: 'Material', hint: 'Light' },
    { theme: 'Shape', hint: 'Compact' },
    { theme: 'Color', hint: 'Pale' },
    { theme: 'Sensory', hint: 'Loud' },
    { theme: 'Location', hint: 'Household' },
    { theme: 'Size', hint: 'Handheld' },
    { theme: 'Sensory', hint: 'Crisp' },
  ],
  Burger: [
    { theme: 'Purpose', hint: 'Filling' },
    { theme: 'Material', hint: 'Rich' },
    { theme: 'Shape', hint: 'Layered' },
    { theme: 'Color', hint: 'Dark' },
    { theme: 'Sensory', hint: 'Fragrant' },
    { theme: 'Location', hint: 'Household' },
    { theme: 'Size', hint: 'Handheld' },
    { theme: 'Purpose', hint: 'Comforting' },
  ],
  'Ice Cream': [
    { theme: 'Purpose', hint: 'Comforting' },
    { theme: 'Material', hint: 'Soft' },
    { theme: 'Shape', hint: 'Smooth' },
    { theme: 'Color', hint: 'Pale' },
    { theme: 'Sensory', hint: 'Cool' },
    { theme: 'Location', hint: 'Household' },
    { theme: 'Size', hint: 'Handheld' },
    { theme: 'Sensory', hint: 'Sweet' },
  ],
  Garlic: [
    { theme: 'Purpose', hint: 'Flavorful' },
    { theme: 'Material', hint: 'Natural' },
    { theme: 'Shape', hint: 'Compact' },
    { theme: 'Color', hint: 'Pale' },
    { theme: 'Sensory', hint: 'Fragrant' },
    { theme: 'Location', hint: 'Kitchen' },
    { theme: 'Size', hint: 'Handheld' },
    { theme: 'Sensory', hint: 'Tangy' },
  ],
  Mushroom: [
    { theme: 'Purpose', hint: 'Nourishing' },
    { theme: 'Material', hint: 'Natural' },
    { theme: 'Shape', hint: 'Round' },
    { theme: 'Color', hint: 'Neutral' },
    { theme: 'Sensory', hint: 'Fragrant' },
    { theme: 'Location', hint: 'Outdoors' },
    { theme: 'Size', hint: 'Handheld' },
    { theme: 'Sensory', hint: 'Earthy' },
  ],
  Sushi: [
    { theme: 'Purpose', hint: 'Filling' },
    { theme: 'Material', hint: 'Delicate' },
    { theme: 'Shape', hint: 'Compact' },
    { theme: 'Color', hint: 'Bright' },
    { theme: 'Sensory', hint: 'Fragrant' },
    { theme: 'Location', hint: 'Kitchen' },
    { theme: 'Size', hint: 'Handheld' },
    { theme: 'Purpose', hint: 'Refreshing' },
  ],

  // ==================== Object ====================
  Chair: [
    { theme: 'Purpose', hint: 'Support' },
    { theme: 'Material', hint: 'Hard' },
    { theme: 'Shape', hint: 'Angular' },
    { theme: 'Color', hint: 'Neutral' },
    { theme: 'Sensory', hint: 'Sturdy' },
    { theme: 'Location', hint: 'Indoor' },
    { theme: 'Size', hint: 'Human-scale' },
    { theme: 'Material', hint: 'Wooden' },
  ],
  Bottle: [
    { theme: 'Purpose', hint: 'Stores' },
    { theme: 'Material', hint: 'Glass' },
    { theme: 'Shape', hint: 'Round' },
    { theme: 'Color', hint: 'Clear' },
    { theme: 'Sensory', hint: 'Smooth' },
    { theme: 'Location', hint: 'Kitchen' },
    { theme: 'Size', hint: 'Handheld' },
    { theme: 'Shape', hint: 'Narrow-necked' },
  ],
  Pillow: [
    { theme: 'Purpose', hint: 'Comforting' },
    { theme: 'Material', hint: 'Soft' },
    { theme: 'Shape', hint: 'Compact' },
    { theme: 'Color', hint: 'Pale' },
    { theme: 'Sensory', hint: 'Warm' },
    { theme: 'Location', hint: 'Household' },
    { theme: 'Size', hint: 'Human-scale' },
    { theme: 'Purpose', hint: 'Support' },
  ],
  Key: [
    { theme: 'Purpose', hint: 'Unlocks' },
    { theme: 'Material', hint: 'Metal' },
    { theme: 'Shape', hint: 'Angular' },
    { theme: 'Color', hint: 'Neutral' },
    { theme: 'Sensory', hint: 'Smooth' },
    { theme: 'Location', hint: 'Household' },
    { theme: 'Size', hint: 'Tiny' },
    { theme: 'Shape', hint: 'Compact' },
  ],
  Fork: [
    { theme: 'Purpose', hint: 'Support' },
    { theme: 'Material', hint: 'Metal' },
    { theme: 'Shape', hint: 'Angular' },
    { theme: 'Color', hint: 'Neutral' },
    { theme: 'Sensory', hint: 'Smooth' },
    { theme: 'Location', hint: 'Kitchen' },
    { theme: 'Size', hint: 'Handheld' },
    { theme: 'Shape', hint: 'Elongated' },
  ],
  Candle: [
    { theme: 'Purpose', hint: 'Illuminates' },
    { theme: 'Material', hint: 'Soft' },
    { theme: 'Shape', hint: 'Elongated' },
    { theme: 'Color', hint: 'Pale' },
    { theme: 'Sensory', hint: 'Warm' },
    { theme: 'Location', hint: 'Household' },
    { theme: 'Size', hint: 'Handheld' },
    { theme: 'Sensory', hint: 'Fragrant' },
  ],
  Sock: [
    { theme: 'Purpose', hint: 'Protective' },
    { theme: 'Material', hint: 'Fabric' },
    { theme: 'Shape', hint: 'Fitted' },
    { theme: 'Color', hint: 'Neutral' },
    { theme: 'Sensory', hint: 'Soft' },
    { theme: 'Location', hint: 'Closet' },
    { theme: 'Size', hint: 'Small-to-medium' },
    { theme: 'Purpose', hint: 'Seasonal' },
  ],
  Mirror: [
    { theme: 'Purpose', hint: 'Reflects' },
    { theme: 'Material', hint: 'Glass' },
    { theme: 'Shape', hint: 'Flat' },
    { theme: 'Color', hint: 'Clear' },
    { theme: 'Sensory', hint: 'Smooth' },
    { theme: 'Location', hint: 'Household' },
    { theme: 'Size', hint: 'Human-scale' },
    { theme: 'Shape', hint: 'Round' },
  ],
  Knife: [
    { theme: 'Purpose', hint: 'Cuts' },
    { theme: 'Material', hint: 'Metal' },
    { theme: 'Shape', hint: 'Elongated' },
    { theme: 'Color', hint: 'Neutral' },
    { theme: 'Sensory', hint: 'Smooth' },
    { theme: 'Location', hint: 'Kitchen' },
    { theme: 'Size', hint: 'Handheld' },
    { theme: 'Purpose', hint: 'Dangerous' },
  ],
  Bag: [
    { theme: 'Purpose', hint: 'Stores' },
    { theme: 'Material', hint: 'Fabric' },
    { theme: 'Shape', hint: 'Compact' },
    { theme: 'Color', hint: 'Dark' },
    { theme: 'Sensory', hint: 'Sturdy' },
    { theme: 'Location', hint: 'Closet' },
    { theme: 'Size', hint: 'Human-scale' },
    { theme: 'Purpose', hint: 'Portable' },
  ],
  Clock: [
    { theme: 'Purpose', hint: 'Structured' },
    { theme: 'Material', hint: 'Metal' },
    { theme: 'Shape', hint: 'Round' },
    { theme: 'Color', hint: 'Neutral' },
    { theme: 'Sensory', hint: 'Loud' },
    { theme: 'Location', hint: 'Household' },
    { theme: 'Size', hint: 'Human-scale' },
    { theme: 'Shape', hint: 'Compact' },
  ],
  Book: [
    { theme: 'Purpose', hint: 'Educational' },
    { theme: 'Material', hint: 'Natural' },
    { theme: 'Shape', hint: 'Layered' },
    { theme: 'Color', hint: 'Pale' },
    { theme: 'Sensory', hint: 'Quiet' },
    { theme: 'Location', hint: 'Household' },
    { theme: 'Size', hint: 'Handheld' },
    { theme: 'Purpose', hint: 'Recreational' },
  ],
  Pen: [
    { theme: 'Purpose', hint: 'Writes' },
    { theme: 'Material', hint: 'Metal' },
    { theme: 'Shape', hint: 'Elongated' },
    { theme: 'Color', hint: 'Dark' },
    { theme: 'Sensory', hint: 'Smooth' },
    { theme: 'Location', hint: 'Household' },
    { theme: 'Size', hint: 'Tiny' },
    { theme: 'Shape', hint: 'Compact' },
  ],
  Soap: [
    { theme: 'Purpose', hint: 'Cleansing' },
    { theme: 'Material', hint: 'Soft' },
    { theme: 'Shape', hint: 'Compact' },
    { theme: 'Color', hint: 'Pale' },
    { theme: 'Sensory', hint: 'Fragrant' },
    { theme: 'Location', hint: 'Household' },
    { theme: 'Size', hint: 'Handheld' },
    { theme: 'Sensory', hint: 'Smooth' },
  ],
  Blanket: [
    { theme: 'Purpose', hint: 'Comforting' },
    { theme: 'Material', hint: 'Fabric' },
    { theme: 'Shape', hint: 'Spacious' },
    { theme: 'Color', hint: 'Muted' },
    { theme: 'Sensory', hint: 'Warm' },
    { theme: 'Location', hint: 'Household' },
    { theme: 'Size', hint: 'Human-scale' },
    { theme: 'Sensory', hint: 'Soft' },
  ],
  Phone: [
    { theme: 'Purpose', hint: 'Connects' },
    { theme: 'Material', hint: 'Glass' },
    { theme: 'Shape', hint: 'Flat' },
    { theme: 'Color', hint: 'Dark' },
    { theme: 'Sensory', hint: 'Smooth' },
    { theme: 'Location', hint: 'Household' },
    { theme: 'Size', hint: 'Handheld' },
    { theme: 'Purpose', hint: 'Portable' },
  ],
  Lamp: [
    { theme: 'Purpose', hint: 'Illuminates' },
    { theme: 'Material', hint: 'Metal' },
    { theme: 'Shape', hint: 'Angular' },
    { theme: 'Color', hint: 'Bright' },
    { theme: 'Sensory', hint: 'Warm' },
    { theme: 'Location', hint: 'Indoor' },
    { theme: 'Size', hint: 'Human-scale' },
    { theme: 'Purpose', hint: 'Decorative' },
  ],
  Stairs: [
    { theme: 'Purpose', hint: 'Connects' },
    { theme: 'Material', hint: 'Built' },
    { theme: 'Shape', hint: 'Angular' },
    { theme: 'Color', hint: 'Neutral' },
    { theme: 'Sensory', hint: 'Sturdy' },
    { theme: 'Location', hint: 'Indoor' },
    { theme: 'Size', hint: 'Large' },
    { theme: 'Shape', hint: 'Elongated' },
  ],
  Cup: [
    { theme: 'Purpose', hint: 'Stores' },
    { theme: 'Material', hint: 'Glass' },
    { theme: 'Shape', hint: 'Round' },
    { theme: 'Color', hint: 'Clear' },
    { theme: 'Sensory', hint: 'Smooth' },
    { theme: 'Location', hint: 'Kitchen' },
    { theme: 'Size', hint: 'Handheld' },
    { theme: 'Shape', hint: 'Compact' },
  ],
  Box: [
    { theme: 'Purpose', hint: 'Stores' },
    { theme: 'Material', hint: 'Built' },
    { theme: 'Shape', hint: 'Angular' },
    { theme: 'Color', hint: 'Neutral' },
    { theme: 'Sensory', hint: 'Sturdy' },
    { theme: 'Location', hint: 'Household' },
    { theme: 'Size', hint: 'Human-scale' },
    { theme: 'Shape', hint: 'Compact' },
  ],

  // ==================== Nature ====================
  Rain: [
    { theme: 'Purpose', hint: 'Nourishing' },
    { theme: 'Material', hint: 'Liquid' },
    { theme: 'Shape', hint: 'Scattered' },
    { theme: 'Color', hint: 'Clear' },
    { theme: 'Sensory', hint: 'Cool' },
    { theme: 'Location', hint: 'Outdoors' },
    { theme: 'Size', hint: 'Large' },
    { theme: 'Sensory', hint: 'Loud' },
  ],
  Sun: [
    { theme: 'Purpose', hint: 'Illuminates' },
    { theme: 'Material', hint: 'Natural' },
    { theme: 'Shape', hint: 'Round' },
    { theme: 'Color', hint: 'Bright' },
    { theme: 'Sensory', hint: 'Warm' },
    { theme: 'Location', hint: 'Outdoors' },
    { theme: 'Size', hint: 'Large' },
    { theme: 'Purpose', hint: 'Landmark' },
  ],
  River: [
    { theme: 'Purpose', hint: 'Nourishing' },
    { theme: 'Material', hint: 'Liquid' },
    { theme: 'Shape', hint: 'Elongated' },
    { theme: 'Color', hint: 'Clear' },
    { theme: 'Sensory', hint: 'Cool' },
    { theme: 'Location', hint: 'Outdoors' },
    { theme: 'Size', hint: 'Large' },
    { theme: 'Sensory', hint: 'Flowing' },
  ],
  Mountain: [
    { theme: 'Purpose', hint: 'Landmark' },
    { theme: 'Material', hint: 'Natural' },
    { theme: 'Shape', hint: 'Angular' },
    { theme: 'Color', hint: 'Muted' },
    { theme: 'Sensory', hint: 'Cold' },
    { theme: 'Location', hint: 'Outdoors' },
    { theme: 'Size', hint: 'Large' },
    { theme: 'Shape', hint: 'Towering' },
  ],
  Forest: [
    { theme: 'Purpose', hint: 'Recreational' },
    { theme: 'Material', hint: 'Natural' },
    { theme: 'Shape', hint: 'Spacious' },
    { theme: 'Color', hint: 'Muted' },
    { theme: 'Sensory', hint: 'Quiet' },
    { theme: 'Location', hint: 'Outdoors' },
    { theme: 'Size', hint: 'Large' },
    { theme: 'Purpose', hint: 'Landmark' },
  ],
  Sand: [
    { theme: 'Purpose', hint: 'Recreational' },
    { theme: 'Material', hint: 'Natural' },
    { theme: 'Shape', hint: 'Scattered' },
    { theme: 'Color', hint: 'Pale' },
    { theme: 'Sensory', hint: 'Rough' },
    { theme: 'Location', hint: 'Outdoors' },
    { theme: 'Size', hint: 'Large' },
    { theme: 'Sensory', hint: 'Warm' },
  ],
  Cloud: [
    { theme: 'Purpose', hint: 'Drifting' },
    { theme: 'Material', hint: 'Natural' },
    { theme: 'Shape', hint: 'Round' },
    { theme: 'Color', hint: 'Pale' },
    { theme: 'Sensory', hint: 'Cool' },
    { theme: 'Location', hint: 'Outdoors' },
    { theme: 'Size', hint: 'Large' },
    { theme: 'Sensory', hint: 'Quiet' },
  ],
  Fire: [
    { theme: 'Purpose', hint: 'Illuminates' },
    { theme: 'Material', hint: 'Natural' },
    { theme: 'Shape', hint: 'Flickering' },
    { theme: 'Color', hint: 'Bright' },
    { theme: 'Sensory', hint: 'Warm' },
    { theme: 'Location', hint: 'Outdoors' },
    { theme: 'Size', hint: 'Large' },
    { theme: 'Purpose', hint: 'Dangerous' },
  ],
  Cave: [
    { theme: 'Purpose', hint: 'Landmark' },
    { theme: 'Material', hint: 'Natural' },
    { theme: 'Shape', hint: 'Hollow' },
    { theme: 'Color', hint: 'Dark' },
    { theme: 'Sensory', hint: 'Cold' },
    { theme: 'Location', hint: 'Outdoors' },
    { theme: 'Size', hint: 'Large' },
    { theme: 'Sensory', hint: 'Quiet' },
  ],
  Island: [
    { theme: 'Purpose', hint: 'Landmark' },
    { theme: 'Material', hint: 'Natural' },
    { theme: 'Shape', hint: 'Elongated' },
    { theme: 'Color', hint: 'Muted' },
    { theme: 'Sensory', hint: 'Warm' },
    { theme: 'Location', hint: 'Outdoors' },
    { theme: 'Size', hint: 'Large' },
    { theme: 'Purpose', hint: 'Recreational' },
  ],
  Wind: [
    { theme: 'Purpose', hint: 'Drifting' },
    { theme: 'Material', hint: 'Natural' },
    { theme: 'Shape', hint: 'Scattered' },
    { theme: 'Color', hint: 'Clear' },
    { theme: 'Sensory', hint: 'Cool' },
    { theme: 'Location', hint: 'Outdoors' },
    { theme: 'Size', hint: 'Large' },
    { theme: 'Sensory', hint: 'Loud' },
  ],
  Leaf: [
    { theme: 'Purpose', hint: 'Decorative' },
    { theme: 'Material', hint: 'Delicate' },
    { theme: 'Shape', hint: 'Flat' },
    { theme: 'Color', hint: 'Bright' },
    { theme: 'Sensory', hint: 'Crisp' },
    { theme: 'Location', hint: 'Outdoors' },
    { theme: 'Size', hint: 'Small-to-medium' },
    { theme: 'Shape', hint: 'Curved' },
  ],
  Stone: [
    { theme: 'Purpose', hint: 'Built' },
    { theme: 'Material', hint: 'Hard' },
    { theme: 'Shape', hint: 'Angular' },
    { theme: 'Color', hint: 'Neutral' },
    { theme: 'Sensory', hint: 'Rough' },
    { theme: 'Location', hint: 'Outdoors' },
    { theme: 'Size', hint: 'Small-to-medium' },
    { theme: 'Material', hint: 'Natural' },
  ],
  Ice: [
    { theme: 'Purpose', hint: 'Preserves' },
    { theme: 'Material', hint: 'Hard' },
    { theme: 'Shape', hint: 'Angular' },
    { theme: 'Color', hint: 'Clear' },
    { theme: 'Sensory', hint: 'Cold' },
    { theme: 'Location', hint: 'Outdoors' },
    { theme: 'Size', hint: 'Small-to-medium' },
    { theme: 'Sensory', hint: 'Smooth' },
  ],
  Desert: [
    { theme: 'Purpose', hint: 'Landmark' },
    { theme: 'Material', hint: 'Natural' },
    { theme: 'Shape', hint: 'Spacious' },
    { theme: 'Color', hint: 'Pale' },
    { theme: 'Sensory', hint: 'Warm' },
    { theme: 'Location', hint: 'Outdoors' },
    { theme: 'Size', hint: 'Large' },
    { theme: 'Sensory', hint: 'Dry' },
  ],

  // ==================== Vehicle ====================
  Car: [
    { theme: 'Purpose', hint: 'Transports' },
    { theme: 'Material', hint: 'Metal' },
    { theme: 'Shape', hint: 'Elongated' },
    { theme: 'Color', hint: 'Painted' },
    { theme: 'Sensory', hint: 'Loud' },
    { theme: 'Location', hint: 'Roadside' },
    { theme: 'Size', hint: 'Multi-person' },
    { theme: 'Shape', hint: 'Wheeled' },
  ],
  Bicycle: [
    { theme: 'Purpose', hint: 'Transports' },
    { theme: 'Material', hint: 'Metal' },
    { theme: 'Shape', hint: 'Elongated' },
    { theme: 'Color', hint: 'Painted' },
    { theme: 'Sensory', hint: 'Quiet' },
    { theme: 'Location', hint: 'Roadside' },
    { theme: 'Size', hint: 'Human-scale' },
    { theme: 'Shape', hint: 'Wheeled' },
  ],
  Boat: [
    { theme: 'Purpose', hint: 'Transports' },
    { theme: 'Material', hint: 'Sturdy' },
    { theme: 'Shape', hint: 'Elongated' },
    { theme: 'Color', hint: 'Painted' },
    { theme: 'Sensory', hint: 'Smooth motion' },
    { theme: 'Location', hint: 'Outdoors' },
    { theme: 'Size', hint: 'Multi-person' },
    { theme: 'Purpose', hint: 'Fishing' },
  ],
  Train: [
    { theme: 'Purpose', hint: 'Transports' },
    { theme: 'Material', hint: 'Metal' },
    { theme: 'Shape', hint: 'Elongated' },
    { theme: 'Color', hint: 'Muted' },
    { theme: 'Sensory', hint: 'Loud' },
    { theme: 'Location', hint: 'Public' },
    { theme: 'Size', hint: 'Multi-person' },
    { theme: 'Shape', hint: 'Wheeled' },
  ],
  Plane: [
    { theme: 'Purpose', hint: 'Transports' },
    { theme: 'Material', hint: 'Metal' },
    { theme: 'Shape', hint: 'Elongated' },
    { theme: 'Color', hint: 'Painted' },
    { theme: 'Sensory', hint: 'Loud' },
    { theme: 'Location', hint: 'Public' },
    { theme: 'Size', hint: 'Multi-person' },
    { theme: 'Shape', hint: 'Winged' },
  ],
  Motorbike: [
    { theme: 'Purpose', hint: 'Transports' },
    { theme: 'Material', hint: 'Metal' },
    { theme: 'Shape', hint: 'Elongated' },
    { theme: 'Color', hint: 'Painted' },
    { theme: 'Sensory', hint: 'Loud' },
    { theme: 'Location', hint: 'Roadside' },
    { theme: 'Size', hint: 'Human-scale' },
    { theme: 'Shape', hint: 'Wheeled' },
  ],
  Submarine: [
    { theme: 'Purpose', hint: 'Transports' },
    { theme: 'Material', hint: 'Sturdy' },
    { theme: 'Shape', hint: 'Elongated' },
    { theme: 'Color', hint: 'Dark' },
    { theme: 'Sensory', hint: 'Quiet' },
    { theme: 'Location', hint: 'Outdoors' },
    { theme: 'Size', hint: 'Multi-person' },
    { theme: 'Purpose', hint: 'Structured' },
  ],

  // ==================== Place ====================
  Beach: [
    { theme: 'Purpose', hint: 'Recreational' },
    { theme: 'Material', hint: 'Natural' },
    { theme: 'Shape', hint: 'Elongated' },
    { theme: 'Color', hint: 'Pale' },
    { theme: 'Sensory', hint: 'Warm' },
    { theme: 'Location', hint: 'Outdoors' },
    { theme: 'Size', hint: 'Large' },
    { theme: 'Sensory', hint: 'Breezy' },
  ],
  Market: [
    { theme: 'Purpose', hint: 'Communal' },
    { theme: 'Material', hint: 'Built' },
    { theme: 'Shape', hint: 'Spacious' },
    { theme: 'Color', hint: 'Bright' },
    { theme: 'Sensory', hint: 'Lively' },
    { theme: 'Location', hint: 'Public' },
    { theme: 'Size', hint: 'Large' },
    { theme: 'Purpose', hint: 'Recreational' },
  ],
  Hospital: [
    { theme: 'Purpose', hint: 'Healing' },
    { theme: 'Material', hint: 'Built' },
    { theme: 'Shape', hint: 'Spacious' },
    { theme: 'Color', hint: 'Pale' },
    { theme: 'Sensory', hint: 'Quiet' },
    { theme: 'Location', hint: 'Public' },
    { theme: 'Size', hint: 'Large' },
    { theme: 'Purpose', hint: 'Structured' },
  ],
  School: [
    { theme: 'Purpose', hint: 'Communal' },
    { theme: 'Material', hint: 'Built' },
    { theme: 'Shape', hint: 'Spacious' },
    { theme: 'Color', hint: 'Muted' },
    { theme: 'Sensory', hint: 'Lively' },
    { theme: 'Location', hint: 'Public' },
    { theme: 'Size', hint: 'Large' },
    { theme: 'Purpose', hint: 'Educational' },
  ],
  Restaurant: [
    { theme: 'Purpose', hint: 'Communal' },
    { theme: 'Material', hint: 'Built' },
    { theme: 'Shape', hint: 'Spacious' },
    { theme: 'Color', hint: 'Muted' },
    { theme: 'Sensory', hint: 'Fragrant' },
    { theme: 'Location', hint: 'Public' },
    { theme: 'Size', hint: 'Large' },
    { theme: 'Purpose', hint: 'Comforting' },
  ],
  Park: [
    { theme: 'Purpose', hint: 'Recreational' },
    { theme: 'Material', hint: 'Natural' },
    { theme: 'Shape', hint: 'Spacious' },
    { theme: 'Color', hint: 'Bright' },
    { theme: 'Sensory', hint: 'Lively' },
    { theme: 'Location', hint: 'Public' },
    { theme: 'Size', hint: 'Large' },
    { theme: 'Purpose', hint: 'Communal' },
  ],
  Church: [
    { theme: 'Purpose', hint: 'Communal' },
    { theme: 'Material', hint: 'Built' },
    { theme: 'Shape', hint: 'Spacious' },
    { theme: 'Color', hint: 'Muted' },
    { theme: 'Sensory', hint: 'Quiet' },
    { theme: 'Location', hint: 'Public' },
    { theme: 'Size', hint: 'Large' },
    { theme: 'Purpose', hint: 'Structured' },
  ],

  // ==================== Clothing ====================
  Hat: [
    { theme: 'Purpose', hint: 'Protective' },
    { theme: 'Material', hint: 'Fabric' },
    { theme: 'Shape', hint: 'Round' },
    { theme: 'Color', hint: 'Bright' },
    { theme: 'Sensory', hint: 'Soft' },
    { theme: 'Location', hint: 'Closet' },
    { theme: 'Size', hint: 'Small-to-medium' },
    { theme: 'Shape', hint: 'Brimmed' },
  ],
  Jacket: [
    { theme: 'Purpose', hint: 'Protective' },
    { theme: 'Material', hint: 'Fabric' },
    { theme: 'Shape', hint: 'Fitted' },
    { theme: 'Color', hint: 'Muted' },
    { theme: 'Sensory', hint: 'Warm' },
    { theme: 'Location', hint: 'Closet' },
    { theme: 'Size', hint: 'Body-sized' },
    { theme: 'Purpose', hint: 'Seasonal' },
  ],
  Dress: [
    { theme: 'Purpose', hint: 'Seasonal' },
    { theme: 'Material', hint: 'Fabric' },
    { theme: 'Shape', hint: 'Fitted' },
    { theme: 'Color', hint: 'Bright' },
    { theme: 'Sensory', hint: 'Soft' },
    { theme: 'Location', hint: 'Closet' },
    { theme: 'Size', hint: 'Body-sized' },
    { theme: 'Purpose', hint: 'Decorative' },
  ],
  Boots: [
    { theme: 'Purpose', hint: 'Protective' },
    { theme: 'Material', hint: 'Sturdy' },
    { theme: 'Shape', hint: 'Fitted' },
    { theme: 'Color', hint: 'Dark' },
    { theme: 'Sensory', hint: 'Rough' },
    { theme: 'Location', hint: 'Closet' },
    { theme: 'Size', hint: 'Body-sized' },
    { theme: 'Material', hint: 'Durable' },
  ],
  Scarf: [
    { theme: 'Purpose', hint: 'Protective' },
    { theme: 'Material', hint: 'Fabric' },
    { theme: 'Shape', hint: 'Elongated' },
    { theme: 'Color', hint: 'Muted' },
    { theme: 'Sensory', hint: 'Warm' },
    { theme: 'Location', hint: 'Closet' },
    { theme: 'Size', hint: 'Body-sized' },
    { theme: 'Purpose', hint: 'Seasonal' },
  ],
};
