export const ALL_WORDS = [
  {cat:"Animal",w:["Dog","Wolf"]},{cat:"Animal",w:["Cat","Lynx"]},{cat:"Animal",w:["Frog","Toad"]},
  {cat:"Animal",w:["Shark","Dolphin"]},{cat:"Animal",w:["Chicken","Duck"]},{cat:"Animal",w:["Horse","Donkey"]},
  {cat:"Animal",w:["Cow","Bison"]},{cat:"Animal",w:["Rabbit","Hare"]},{cat:"Animal",w:["Bee","Wasp"]},
  {cat:"Animal",w:["Owl","Hawk"]},{cat:"Animal",w:["Pig","Boar"]},{cat:"Animal",w:["Snake","Lizard"]},
  {cat:"Animal",w:["Crab","Lobster"]},{cat:"Animal",w:["Elephant","Rhino"]},{cat:"Animal",w:["Lion","Tiger"]},
  {cat:"Animal",w:["Penguin","Seal"]},{cat:"Animal",w:["Spider","Scorpion"]},{cat:"Animal",w:["Parrot","Crow"]},
  {cat:"Animal",w:["Salmon","Trout"]},{cat:"Animal",w:["Gorilla","Chimp"]},
  {cat:"Food",w:["Apple","Pear"]},{cat:"Food",w:["Pizza","Flatbread"]},{cat:"Food",w:["Banana","Mango"]},
  {cat:"Food",w:["Bread","Toast"]},{cat:"Food",w:["Butter","Cheese"]},{cat:"Food",w:["Milk","Yogurt"]},
  {cat:"Food",w:["Coffee","Tea"]},{cat:"Food",w:["Orange","Tangerine"]},{cat:"Food",w:["Honey","Jam"]},
  {cat:"Food",w:["Soup","Stew"]},{cat:"Food",w:["Cake","Muffin"]},{cat:"Food",w:["Egg","Omelette"]},
  {cat:"Food",w:["Rice","Couscous"]},{cat:"Food",w:["Pasta","Noodles"]},{cat:"Food",w:["Steak","Chop"]},
  {cat:"Food",w:["Salad","Coleslaw"]},{cat:"Food",w:["Chocolate","Caramel"]},{cat:"Food",w:["Lemon","Lime"]},
  {cat:"Food",w:["Strawberry","Cherry"]},{cat:"Food",w:["Popcorn","Chips"]},{cat:"Food",w:["Burger","Sandwich"]},
  {cat:"Food",w:["Ice Cream","Gelato"]},{cat:"Food",w:["Garlic","Onion"]},{cat:"Food",w:["Mushroom","Truffle"]},
  {cat:"Food",w:["Sushi","Sashimi"]},
  {cat:"Object",w:["Chair","Stool"]},{cat:"Object",w:["Pillow","Cushion"]},{cat:"Object",w:["Key","Lock"]},
  {cat:"Object",w:["Fork","Spoon"]},{cat:"Object",w:["Candle","Torch"]},{cat:"Object",w:["Sock","Glove"]},
  {cat:"Object",w:["Mirror","Window"]},{cat:"Object",w:["Knife","Scissors"]},{cat:"Object",w:["Bottle","Jar"]},
  {cat:"Object",w:["Bag","Backpack"]},{cat:"Object",w:["Clock","Watch"]},{cat:"Object",w:["Book","Magazine"]},
  {cat:"Object",w:["Pen","Pencil"]},{cat:"Object",w:["Soap","Shampoo"]},{cat:"Object",w:["Blanket","Towel"]},
  {cat:"Object",w:["Phone","Tablet"]},{cat:"Object",w:["Lamp","Flashlight"]},{cat:"Object",w:["Stairs","Ladder"]},
  {cat:"Object",w:["Cup","Glass"]},{cat:"Object",w:["Box","Crate"]},
  {cat:"Nature",w:["Rain","Snow"]},{cat:"Nature",w:["Sun","Moon"]},{cat:"Nature",w:["River","Stream"]},
  {cat:"Nature",w:["Mountain","Hill"]},{cat:"Nature",w:["Forest","Jungle"]},{cat:"Nature",w:["Sand","Mud"]},
  {cat:"Nature",w:["Cloud","Fog"]},{cat:"Nature",w:["Fire","Smoke"]},{cat:"Nature",w:["Cave","Tunnel"]},
  {cat:"Nature",w:["Island","Peninsula"]},{cat:"Nature",w:["Wind","Storm"]},{cat:"Nature",w:["Leaf","Petal"]},
  {cat:"Nature",w:["Stone","Brick"]},{cat:"Nature",w:["Ice","Frost"]},{cat:"Nature",w:["Desert","Dune"]},
  {cat:"Vehicle",w:["Car","Truck"]},{cat:"Vehicle",w:["Bicycle","Scooter"]},{cat:"Vehicle",w:["Boat","Ferry"]},
  {cat:"Vehicle",w:["Train","Tram"]},{cat:"Vehicle",w:["Plane","Helicopter"]},{cat:"Vehicle",w:["Motorbike","Quad"]},
  {cat:"Vehicle",w:["Submarine","Yacht"]},
  {cat:"Place",w:["Beach","Lake"]},{cat:"Place",w:["Market","Mall"]},{cat:"Place",w:["Hospital","Clinic"]},
  {cat:"Place",w:["School","Library"]},{cat:"Place",w:["Restaurant","Café"]},{cat:"Place",w:["Park","Garden"]},
  {cat:"Place",w:["Church","Temple"]},
  {cat:"Clothing",w:["Hat","Cap"]},{cat:"Clothing",w:["Jacket","Coat"]},{cat:"Clothing",w:["Dress","Skirt"]},
  {cat:"Clothing",w:["Boots","Sandals"]},{cat:"Clothing",w:["Scarf","Tie"]},
];

export const ALL_CATS = [...new Set(ALL_WORDS.map(w => w.cat))];
